eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#开启hystrix fallback
feign:
  hystrix:
    enabled: true
server:
  port: 8765
spring:
  application:
    name: service-feign