server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/AkiraLiu39/learn-cloud/
          searchPaths: config-server/src/main/resources/cloud-config
#          username: your username
#          password: your password

#集群配置，注册eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/